"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

# Load environment variables from .env, overriding any system-level vars
load_dotenv(override=True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Require environment variable for SECRET_KEY (no hardcoded fallback)
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
# Accept typical boolean env values: 1/true/yes/on
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip()
                 for h in _allowed_hosts.split(',') if h.strip()] or ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',                       # Jazzmin theme (primary)
    'django.contrib.admin',          # core admin
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # CORS
    'corsheaders',
    # Editors
    'ckeditor',            # still used by Blog for now
    'ckeditor_uploader',   # v4 uploader (legacy)
    'django_ckeditor_5',   # CKEditor 5 for Homepage editing
    'adminsortable2',
    'django_editorjs_fields',
    # Project apps
    'content',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# Parse DATABASE_URL for Neon PostgreSQL; no hardcoded values.
_DATABASE_URL = os.getenv('DATABASE_URL')
if not _DATABASE_URL:
    raise RuntimeError('DATABASE_URL environment variable is required')

_pg = urlparse(_DATABASE_URL)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _pg.path.replace('/', ''),
        'USER': _pg.username,
        'PASSWORD': _pg.password,
        'HOST': _pg.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(_pg.query)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# In production, collectstatic will write here
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SITE_ID = 1

# CKEditor uploader configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_ALLOW_NONIMAGE_FILES = True

# CKEditor rich toolbar for admin editing
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            ['Source', 'Cut', 'Copy', 'Paste', 'PasteText', 'Undo', 'Redo'],
            ['Find', 'Replace', 'SelectAll', 'RemoveFormat'],
            ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList', 'Outdent', 'Indent', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor', 'SetID'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'],
            ['Styles', 'Format', 'Font', 'FontSize', 'TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks']
        ],
        'height': 400,
        'width': '100%',
        'extraPlugins': ','.join([
            'uploadimage',  # image upload button
            # remove video/iframe related plugins from homepage editor
            'autogrow',
            'codesnippet',
            'table', 'tableresize',
            'justify',      # left/center/right alignment
            'font',         # font family and size
            'colorbutton', 'colordialog',  # text/background color
            'setid',        # custom Set ID button
        ]),
        'allowedContent': True,  # allow inline styles/classes from CKEditor
        # Explicitly disallow video/source/iframe tags in the homepage editor
        'disallowedContent': 'iframe;video;source',
        'removePlugins': 'resize',
        'fontSize_sizes': '12/12px;14/14px;16/16px;18/18px;20/20px;24/24px;28/28px;32/32px',
        # Show full Image dialog with URL + Upload + Advanced
        # Do not remove any dialog tabs to give full control
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'contentsCss': ['/static/admin/css/base.css'],
        # Provide styles to turn links into buttons directly from Styles combo
        'stylesSet': [
            {'name': 'Button', 'element': 'a', 'attributes': {'class': 'btn'}},
            {'name': 'Primary Button', 'element': 'a',
                'attributes': {'class': 'btn btn-primary'}},
        ],
        'format_tags': 'p;h2;h3;h4',
        # Auto-embed provider for URLs (YouTube/Vimeo, etc.)
        # Disable external oEmbed provider to avoid cross-origin fetch issues
        # 'embed_provider': '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}',
    },
}

# CKEditor 5 configuration (used by Homepage and Sections)
CKEDITOR_5_CONFIGS = {
    'default': {
        'language': 'en',
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'link', 'underline', 'strikethrough', '|',
            'bulletedList', 'numberedList', 'outdent', 'indent', '|',
            'blockQuote', 'insertTable', 'undo', 'redo', '|',
            'codeBlock', 'horizontalLine', 'imageUpload', 'mediaEmbed', 'htmlEmbed'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:inline', 'imageStyle:block',
                'imageStyle:side', 'linkImage'
            ]
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells']
        },
        # Allow ids/classes on links, spans, headings, paragraphs for anchor usage
        'htmlSupport': {
            'allow': [
                {'name': 'a', 'attributes': {'id': True,
                                             'class': True, 'target': True, 'rel': True}},
                {'name': 'span', 'attributes': {'id': True, 'class': True}},
                {'name': 'p', 'attributes': {'id': True, 'class': True}},
                {'name': 'h2', 'attributes': {'id': True, 'class': True}},
                {'name': 'h3', 'attributes': {'id': True, 'class': True}},
                {'name': 'h4', 'attributes': {'id': True, 'class': True}},
                # Allow iframe embeds inside CKEditor 5 content blocks
                {'name': 'iframe', 'attributes': {
                    'src': True,
                    'width': True,
                    'height': True,
                    'allow': True,
                    'allowfullscreen': True,
                    'frameborder': True,
                    'referrerpolicy': True,
                    'loading': True,
                    'class': True,
                    'style': True
                }}
            ]
        },
        # Link decorators to toggle "Button" style on links
        'link': {
            'decorators': {
                'isButton': {
                    'mode': 'manual',
                    'label': 'Button',
                    'attributes': {
                        'class': 'btn btn-primary'
                    }
                },
                'newTab': {
                    'mode': 'manual',
                    'label': 'Open in new tab',
                    'attributes': {
                        'target': '_blank',
                        'rel': 'noopener noreferrer'
                    }
                }
            }
        },
    }
}
LANGUAGES = [
    ('en-us', 'English'),
]
# EditorJS tools configuration for admin block editor
EDITOR_JS_CONFIGS = {
    'default': {
        'holder': 'editorjs',
        'tools': {
            'header': {'inlineToolbar': True},
            'paragraph': {'inlineToolbar': True},
            'list': {'inlineToolbar': True},
            'table': {},
            'image': {
                'endpoints': {
                    # Django will reverse these names to full URLs
                    'byFile': 'editorjs_image_upload',
                    'byUrl': 'editorjs_image_by_url',
                }
            },
            'linkTool': {
                'endpoint': 'editorjs_linktool'
            },
            'quote': {},
            'code': {},
            'embed': {
                'config': {
                    'services': {
                        'youtube': True,
                        'vimeo': True,
                        'codepen': True,
                    }
                }
            },
            'delimiter': {},
            'checklist': {},
        }
    }
}

# CSRF Trusted Origins
# Allow override via env (comma-separated URLs). Default to local dev.
_csrf_origins = os.getenv(
    'DJANGO_CSRF_TRUSTED_ORIGINS',
    'http://localhost:8000,http://127.0.0.1:8000'
)
CSRF_TRUSTED_ORIGINS = [o.strip()
                        for o in _csrf_origins.split(',') if o.strip()]


# Minimal Jazzmin branding (optional)
JAZZMIN_SETTINGS = {
    "site_title": "Admin",
    "site_header": "Admin",
    "welcome_sign": "Welcome to Admin",
}

# Email settings from environment (SMTP)
EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes', 'on')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('1', 'true', 'yes', 'on')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'noreply@example.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
