# Generated by Django 5.2.7 on 2025-11-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='home', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('media', 'Media'), ('video', 'Video'), ('stats', 'Stats'), ('graph', 'Graph'), ('code', 'Code'), ('cta', 'CTA')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=50)),
                ('code', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, help_text='List of objects: {label, value}', null=True)),
                ('chart_config', models.JSONField(blank=True, help_text='Simple config dict for graph rendering', null=True)),
                ('layout', models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)')], default='full', max_length=20)),
                ('background_color', models.CharField(blank=True, help_text='e.g., #ffffff or tailwind token', max_length=30)),
                ('text_color', models.CharField(blank=True, max_length=30)),
                ('published', models.BooleanField(default=True)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
