# Generated by Django 5.2.7 on 2025-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='AutoInsurance.org', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='(800) 308-0987', max_length=30)),
                ('footer_company_links', models.JSONField(blank=True, help_text='[{"label":"About","href":"#"}, ...]', null=True)),
                ('footer_legal_links', models.JSONField(blank=True, help_text='[{"label":"Privacy","href":"#"}, ...]', null=True)),
                ('footer_socials', models.JSONField(blank=True, help_text='[{"name":"Twitter","href":"#"}, ...]', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='body_format',
            field=models.CharField(choices=[('text', 'Plain Text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='cta_text',
            field=models.CharField(blank=True, help_text='CTA button text for cta sections', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='media_gallery',
            field=models.JSONField(blank=True, help_text='List of image URLs or uploaded paths', null=True),
        ),
    ]
