# Generated by Django 5.2.7 on 2025-11-09 10:07

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_siteconfig_homepage_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='editor_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('media', 'Media'), ('video', 'Video'), ('stats', 'Stats'), ('graph', 'Graph'), ('code', 'Code'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], max_length=20),
        ),
    ]
