# Generated by Django 5.2.7 on 2025-11-09 10:11

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_section_editor_blocks_alter_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
    ]
