# Generated by Django 5.2.7 on 2025-11-09 11:23

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_homepage_content_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='col1_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Column 1 blocks (used when layout is split/grid2/grid3)', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col2_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Column 2 blocks', null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col3_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Column 3 blocks', null=True),
        ),
    ]
