# Generated by Django 5.2.7 on 2025-11-09 11:43

import django.db.models.deletion
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_section_col1_blocks_section_col2_blocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='og_images/')),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='anchor_id',
            field=models.CharField(blank=True, help_text='Optional anchor id for linking to this section', max_length=80),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=100)),
                ('href', models.CharField(blank=True, help_text='External or internal URL', max_length=255)),
                ('page_slug', models.CharField(blank=True, help_text='Links to a Page by slug', max_length=100)),
                ('anchor_id', models.CharField(blank=True, help_text='Optional anchor id to append', max_length=80)),
                ('dropdown_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, help_text='Optional EditorJS content shown in dropdown', null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menuitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('media', 'Media'), ('video', 'Video'), ('stats', 'Stats'), ('graph', 'Graph'), ('code', 'Code'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('editor_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('body_format', models.CharField(choices=[('text', 'Plain Text'), ('markdown', 'Markdown'), ('html', 'HTML')], default='text', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('media_gallery', models.JSONField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=50)),
                ('code', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('chart_config', models.JSONField(blank=True, null=True)),
                ('layout', models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)')], default='full', max_length=20)),
                ('col1_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col2_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col3_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('anchor_id', models.CharField(blank=True, max_length=80)),
                ('background_color', models.CharField(blank=True, max_length=30)),
                ('text_color', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(blank=True, max_length=50)),
                ('published', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
