# Generated by Django 5.2.7 on 2025-11-09 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_menu_page_section_anchor_id_menuitem_pagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.CharField(choices=[('main', 'Main Page'), ('category', 'Category Page')], default='main', max_length=20),
        ),
        migrations.AddField(
            model_name='page',
            name='parent_page',
            field=models.ForeignKey(blank=True, help_text='Set for Category pages to indicate which Main page they belong to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_pages', to='content.page'),
        ),
    ]
