# Generated by Django 5.2.7 on 2025-11-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_page_page_type_page_parent_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='col1_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col2_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='col3_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col1_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col2_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='col3_rich',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='type',
            field=models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('rich_columns', 'Rich Columns'), ('media', 'Media'), ('video', 'Video'), ('stats', 'Stats'), ('graph', 'Graph'), ('code', 'Code'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('rich_columns', 'Rich Columns'), ('media', 'Media'), ('video', 'Video'), ('stats', 'Stats'), ('graph', 'Graph'), ('code', 'Code'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], max_length=20),
        ),
    ]
