# Generated by Django 5.2.7 on 2025-11-10 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_create_default_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='parent_page',
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='page',
        ),
        migrations.DeleteModel(
            name='SiteConfig',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageSection',
        ),
    ]
