# Generated by Django 5.2.7 on 2025-11-10 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='state',
        ),
        migrations.RemoveField(
            model_name='category',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
