# Generated by Django 5.2.7 on 2025-11-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_blog_state_remove_category_state_delete_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, default='AutoInsurance.org', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='(800) 308-0987', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('logo_icon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('social_links', models.JSONField(blank=True, help_text='[{"name":"Twitter","href":"https://twitter.com/..."}, ...]', null=True)),
                ('footer_company_links', models.JSONField(blank=True, help_text='[{"label":"About","href":"#"}, ...]', null=True)),
                ('footer_legal_links', models.JSONField(blank=True, help_text='[{"label":"Privacy","href":"#"}, ...]', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
