# Generated by Django 5.2.7 on 2025-11-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='disclaimer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
