# Generated by Django 5.2.7 on 2025-11-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_siteconfig_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='social_links_text',
            field=models.TextField(blank=True, default='', help_text='Enter one social URL per line (e.g., https://facebook.com/yourpage)'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_company_links',
            field=models.JSONField(blank=True, help_text='Deprecated', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='footer_legal_links',
            field=models.JSONField(blank=True, help_text='Deprecated', null=True),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='social_links',
            field=models.JSONField(blank=True, help_text='Legacy format: [{"name":"Twitter","href":"https://twitter.com/..."}, ...]', null=True),
        ),
    ]
