# Generated by Django 5.2.7 on 2025-11-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_siteconfig_social_links_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='social_links_text',
            field=models.TextField(blank=True, default='', help_text='Deprecated: Enter one social URL per line'),
        ),
    ]
