# Generated by Django 5.2.7 on 2025-11-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_siteconfig_facebook_url_siteconfig_instagram_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='logo_icon',
            field=models.FileField(blank=True, null=True, upload_to='site/'),
        ),
    ]
