# Generated by Django 5.2.7 on 2025-11-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_siteconfig_favicon_alter_siteconfig_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='copyright_text',
            field=models.CharField(blank=True, default='', help_text='e.g., "Copyright © 2025 YourBrand"; leave blank to auto-generate', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_height_px',
            field=models.PositiveIntegerField(blank=True, help_text='Logo height in pixels; leave empty to use default', null=True),
        ),
    ]
