# Generated by Django 5.2.7 on 2025-11-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_siteconfig_copyright_text_siteconfig_logo_height_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='company_address',
            field=models.TextField(blank=True, default='', help_text='Company address shown in footer'),
        ),
    ]
