# Generated by Django 5.2.7 on 2025-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_siteconfig_company_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='footer_about_text',
            field=models.TextField(blank=True, default='', help_text='Top footer description text shown under brand name'),
        ),
    ]
