# Generated by Django 5.2.7 on 2025-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_siteconfig_footer_about_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_title',
            field=models.CharField(blank=True, default='', help_text='Main homepage heading, e.g., "Auto insurance made clear."', max_length=255),
        ),
    ]
