# Generated by Django 5.2.7 on 2025-11-10 09:55

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_siteconfig_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='', help_text='Comma-separated keywords')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Optional rich content block (supports images, videos, tables)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Homepage tagline description shown under the hero title', max_length=255, verbose_name='Tagline Description'),
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('anchor_id', models.SlugField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collapsible', models.BooleanField(default=True)),
                ('body', ckeditor.fields.RichTextField(help_text='Rich content supports images, videos, tables, and logos within tables')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.homepage')),
            ],
            options={
                'verbose_name': 'Homepage Section',
                'verbose_name_plural': 'Homepage Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
