# Generated by Django 5.2.7 on 2025-11-10 10:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_homepage_alter_siteconfig_tagline_homepagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Optional rich content block (supports images, videos, tables; supports uploads)', null=True),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Rich content supports images, videos, tables, and logos within tables; supports uploads'),
        ),
    ]
