# Generated by Django 5.2.7 on 2025-11-10 10:29

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_alter_homepage_content_alter_homepagesection_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='col1_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Column 1 content (used when layout has columns)', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col2_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Column 2 content (used when layout has columns)', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col3_rich',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Column 3 content (used when layout has 3 columns)', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='layout',
            field=models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Main body (used when layout is Full)', null=True),
        ),
    ]
