# Generated by Django 5.2.7 on 2025-11-10 12:06

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_homepagesection_col1_rich_homepagesection_col2_rich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='col1_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 1'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='col2_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 2'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='col3_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 3'),
        ),
    ]
