# Generated by Django 5.2.7 on 2025-11-10 12:18

import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_alter_homepage_content_alter_homepagesection_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='background_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='chart_config',
            field=models.JSONField(blank=True, help_text='{"data": [{"label": "A", "value": 10}, ...]}', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col1_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col2_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col3_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='cta_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='editor_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/sections/'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='media_gallery',
            field=models.JSONField(blank=True, help_text='["/media/path1.jpg", "/media/path2.jpg", ...]', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='stats',
            field=models.JSONField(blank=True, help_text='[{"label": "Customers", "value": "1000"}, ...]', null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='type',
            field=models.CharField(choices=[('rich_text', 'Rich Text'), ('rich_columns', 'Rich Columns'), ('media', 'Media'), ('video', 'Video'), ('graph', 'Graph'), ('code', 'Code'), ('gallery', 'Gallery'), ('stats', 'Stats'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], default='rich_text', max_length=20),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
