# Generated by Django 5.2.7 on 2025-11-10 12:27

import django_ckeditor_5.fields
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_homepagesection_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='col4_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col4_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 4'),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='columns_count',
            field=models.PositiveIntegerField(default=1, help_text='1 for full width; 2/3/4 for columns'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='layout',
            field=models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)'), ('grid4', 'Grid (4 Columns)')], default='full', max_length=20),
        ),
    ]
