# Generated by Django 5.2.7 on 2025-11-10 12:33

import django_ckeditor_5.fields
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_homepagesection_col4_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='col5_blocks',
            field=django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepagesection',
            name='col5_rich',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 5'),
        ),
        migrations.AlterField(
            model_name='homepagesection',
            name='layout',
            field=models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)'), ('grid4', 'Grid (4 Columns)'), ('grid5', 'Grid (5 Columns)')], default='full', max_length=20),
        ),
    ]
