# Generated by Django 5.2.7 on 2025-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_homepagesection_col1_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesection',
            name='cta_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
