# Generated by Django 5.2.7 on 2025-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_homepagesection_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='home_anchor_id',
            field=models.SlugField(blank=True, default='', help_text='Optional anchor ID for homepage content section', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_cta_text',
            field=models.CharField(blank=True, default='', help_text='Homepage button label (e.g., "Start Now")', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='home_cta_url',
            field=models.URLField(blank=True, default='', help_text='Homepage button link URL (e.g., https://example.com)'),
        ),
    ]
