# Generated by Django 5.2.7 on 2025-11-12 12:53

import ckeditor_uploader.fields
import django.db.models.deletion
import django_ckeditor_5.fields
import django_editorjs_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0039_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('page_type', models.CharField(choices=[('company', 'Company'), ('legal', 'Legal')], default='company', max_length=20)),
                ('meta_title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('meta_keywords', models.TextField(blank=True, default='')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/hero/')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('anchor_id', models.SlugField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('collapsible', models.BooleanField(default=True)),
                ('background_color', models.CharField(blank=True, default='', max_length=20)),
                ('text_color', models.CharField(blank=True, default='', max_length=20)),
                ('type', models.CharField(choices=[('rich_text', 'Rich Text'), ('rich_columns', 'Rich Columns'), ('media', 'Media'), ('video', 'Video'), ('graph', 'Graph'), ('code', 'Code'), ('gallery', 'Gallery'), ('stats', 'Stats'), ('editor', 'Editor Blocks'), ('cta', 'CTA')], default='rich_text', max_length=20)),
                ('layout', models.CharField(choices=[('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid (2 Columns)'), ('grid3', 'Grid (3 Columns)'), ('grid4', 'Grid (4 Columns)'), ('grid5', 'Grid (5 Columns)')], default='full', max_length=20)),
                ('columns_count', models.PositiveIntegerField(default=1, help_text='1 for full width; 2/3/4 for columns')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Body')),
                ('col1_title', models.CharField(blank=True, default='', max_length=255)),
                ('col1_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('col2_title', models.CharField(blank=True, default='', max_length=255)),
                ('col2_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('col3_title', models.CharField(blank=True, default='', max_length=255)),
                ('col3_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('col4_title', models.CharField(blank=True, default='', max_length=255)),
                ('col4_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('col5_title', models.CharField(blank=True, default='', max_length=255)),
                ('col5_subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('col1_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 1')),
                ('col2_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 2')),
                ('col3_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 3')),
                ('col4_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 4')),
                ('col5_rich', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Column 5')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/sections/')),
                ('video_url', models.URLField(blank=True, default='')),
                ('chart_config', models.JSONField(blank=True, help_text='{"data": [{"label": "A", "value": 10}, ...]}', null=True)),
                ('code', models.TextField(blank=True, default='')),
                ('media_gallery', models.JSONField(blank=True, help_text='["/media/path1.jpg", "/media/path2.jpg", ...]', null=True)),
                ('stats', models.JSONField(blank=True, help_text='[{"label": "Customers", "value": "1000"}, ...]', null=True)),
                ('cta_text', models.CharField(blank=True, default='', max_length=100)),
                ('cta_url', models.URLField(blank=True, default='')),
                ('editor_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col1_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col2_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col3_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col4_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('col5_blocks', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['order', 'id'],
            },
        ),
    ]
