# Generated by Django 5.2.7 on 2025-11-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0040_page_pagesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['footer_order', 'title'], 'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='footer_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='show_in_footer',
            field=models.BooleanField(default=False),
        ),
    ]
