# Generated by Django 5.2.7 on 2025-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0044_hide_editorial_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='accent_orange_hex',
            field=models.CharField(blank=True, default='#c2410c', help_text='Primary orange accent color (hex, e.g., #c2410c). Only this orange will change.', max_length=7),
        ),
    ]
