# Generated by Django 5.2.7 on 2025-11-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0045_siteconfig_accent_orange_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='accent_orange_hover_hex',
            field=models.CharField(blank=True, default='#9a3412', help_text='Hover orange accent color (hex, e.g., #9a3412).', max_length=7),
        ),
    ]
