# Generated by Django 5.2.7 on 2025-11-15 08:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0049_add_blog_author_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Blog Content'),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
