# Generated by Django 5.2.7 on 2025-11-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0050_category_blog_content_category_blog_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog_author_image',
            field=models.ImageField(blank=True, help_text='Author image for this article', null=True, upload_to='blog/authors/'),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_author_name',
            field=models.CharField(blank=True, help_text='Author name for this article', max_length=120, null=True),
        ),
    ]
