# Generated by Django 5.2.7 on 2025-11-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0051_category_blog_author_image_category_blog_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog_author_description',
            field=models.TextField(blank=True, help_text='Short description about the author', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_reviewer_description',
            field=models.TextField(blank=True, help_text='Short description about the reviewer', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_reviewer_image',
            field=models.ImageField(blank=True, help_text='Reviewer image for this article', null=True, upload_to='blog/reviewers/'),
        ),
        migrations.AddField(
            model_name='category',
            name='blog_reviewer_name',
            field=models.CharField(blank=True, help_text='Reviewer name for this article', max_length=120, null=True),
        ),
    ]
