# Generated by Django 5.2.7 on 2025-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0052_category_blog_author_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_description',
            field=models.TextField(blank=True, help_text='Short description about the author', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewer_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/reviewers/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='reviewer_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
