# Generated by Django 5.2.7 on 2025-11-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0053_blog_author_description_blog_reviewer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='accent_gradient_from_hex',
            field=models.CharField(blank=True, default='', help_text='Gradient start color (hex, e.g., #ea580c). Leave blank to use Accent Orange.', max_length=7),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='accent_gradient_to_hex',
            field=models.CharField(blank=True, default='', help_text='Gradient end color (hex, e.g., #c2410c). Leave blank to use Accent Hover.', max_length=7),
        ),
        migrations.AlterField(
            model_name='videoplacement',
            name='position',
            field=models.CharField(choices=[('top', 'Top of homepage')], default='top', help_text='Position where video will appear on homepage', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoplacement',
            name='published',
            field=models.BooleanField(default=True, help_text='Show/hide this video on the homepage'),
        ),
        migrations.AlterField(
            model_name='videoplacement',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional title for the video', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoplacement',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload local video files (MP4, WebM, OGG)', null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='videoplacement',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo, or other supported video platform URL'),
        ),
    ]
