# Generated by Django 5.2.7 on 2025-11-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_add_featured_and_guides_sections'),
        ('content', '0055_seed_siteconfig_singleton'),
    ]

    operations = [
    ]
