# Generated by Django 5.2.7 on 2025-11-20 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0056_merge_20251120_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, help_text='e.g., 4.5 out of 5', max_digits=3, null=True)),
                ('short_description', models.TextField(blank=True, default='')),
                ('short_url', models.URLField(blank=True, default='', help_text='Display link or promo URL')),
                ('domain_url', models.URLField(blank=True, default='', help_text='Company domain (homepage)')),
                ('landing_url', models.URLField(blank=True, default='', help_text='Primary CTA URL for quotes')),
                ('contact_url', models.URLField(blank=True, default='', help_text='Optional contact/support URL')),
                ('published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Company',
                'verbose_name_plural': 'Insurance Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(help_text='US state code, e.g., NY', max_length=2)),
                ('covers_entire_state', models.BooleanField(default=False)),
                ('zip_range_start', models.PositiveIntegerField(blank=True, null=True)),
                ('zip_range_end', models.PositiveIntegerField(blank=True, null=True)),
                ('zip_codes_text', models.TextField(blank=True, default='', help_text='Comma/space separated ZIPs: e.g., 10001,10002 10003')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverages', to='content.insurancecompany')),
            ],
            options={
                'verbose_name': 'Insurance Coverage',
                'verbose_name_plural': 'Insurance Coverages',
                'indexes': [models.Index(fields=['state_code'], name='content_ins_state_c_0d7a18_idx')],
            },
        ),
    ]
