# Generated by Django 5.2.7 on 2025-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0057_insurancecompany_insurancecoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='buttons_border_width_px',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Default button border width in pixels (e.g., 1)', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='buttons_font_weight',
            field=models.CharField(blank=True, default='', help_text='Button font-weight (e.g., 500, 600, bold)', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='buttons_radius_px',
            field=models.PositiveIntegerField(blank=True, default=8, help_text='Default button corner radius in pixels (e.g., 8)', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='buttons_uppercase',
            field=models.BooleanField(default=False, help_text='Make button text uppercase globally'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='headings_font_weight',
            field=models.CharField(blank=True, default='', help_text='Headings font-weight (e.g., 700, 800, bold)', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='links_font_weight',
            field=models.CharField(blank=True, default='', help_text='Link font-weight (e.g., 500, 600)', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='links_underline',
            field=models.BooleanField(default=False, help_text='Underline links globally'),
        ),
    ]
