# Generated by Django 5.2.7 on 2025-11-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0060_siteconfig_from_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='home_cta_url',
            field=models.CharField(blank=True, default='', help_text='Homepage button link URL (e.g., https://example.com or /quotes)', max_length=255),
        ),
    ]
