# Generated by Django 5.2.7 on 2025-11-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0061_alter_homepage_home_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='footer_address',
            field=models.TextField(blank=True, default='', help_text='Address to be displayed in footer for this article'),
        ),
    ]
