# Generated by Django 5.2.7 on 2025-12-20 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0063_presslogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presslogo',
            name='image',
            field=models.FileField(help_text='Upload logo image (JPG, PNG, SVG, WebP supported)', upload_to='press_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
