# Generated by Django 5.2.7 on 2025-12-20 12:41

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0065_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_bottom',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Bottom Content (CKEditor 2)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Top Content (CKEditor 1)'),
        ),
        migrations.CreateModel(
            name='PressItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='press/')),
                ('date', models.DateField(blank=True, help_text='Date of the press release/article', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('page', models.ForeignKey(help_text='Page where this press item appears', on_delete=django.db.models.deletion.CASCADE, related_name='press_items', to='content.page')),
            ],
            options={
                'verbose_name': 'Press Item',
                'verbose_name_plural': 'Press Items',
                'ordering': ['order', '-date'],
            },
        ),
    ]
