# Generated by Django 5.2.7 on 2025-12-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0066_page_content_bottom_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category & Blogs', 'verbose_name_plural': 'Category & Blogs'},
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teammember',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
