# Generated by Django 5.2.7 on 2025-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0068_blog_meta_description_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='meta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_keywords',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
