# Generated by Django 5.2.7 on 2025-12-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0069_mainpage_meta_description_mainpage_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='cta_text',
            field=models.CharField(blank=True, default='View My Quote', help_text='Button text', max_length=50),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='features',
            field=models.TextField(blank=True, default='', help_text='Bullet points (one per line)'),
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='headline',
            field=models.CharField(blank=True, default='', help_text="Marketing headline (e.g., 'New Hampshire Drivers Can Save...')", max_length=255),
        ),
    ]
