# Generated by Django 5.2.7 on 2025-11-10 10:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('rich_text', 0), ('columns2', 2), ('columns3', 3), ('image', 4), ('embed', 5)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table']}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed', 'h3', 'h4', 'table']}), 2: ('wagtail.blocks.StructBlock', [[('col1', 1), ('col2', 1)]], {}), 3: ('wagtail.blocks.StructBlock', [[('col1', 1), ('col2', 1), ('col3', 1)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.URLBlock', (), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Wagtail Homepage',
                'verbose_name_plural': 'Wagtail Homepage',
            },
            bases=('wagtailcore.page',),
        ),
    ]
