# Generated by Django 5.2.7 on 2025-11-10 10:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 9), ('rich_text', 2), ('columns2', 4), ('columns3', 5), ('image', 6), ('embed', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid 2'), ('grid3', 'Grid 3')], 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table']}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed', 'h3', 'h4', 'table']}), 4: ('wagtail.blocks.StructBlock', [[('col1', 3), ('col2', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('col1', 3), ('col2', 3), ('col3', 3)]], {}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 7: ('wagtail.blocks.URLBlock', (), {}), 8: ('wagtail.blocks.StreamBlock', [[('rich_text', 2), ('columns2', 4), ('columns3', 5), ('image', 6), ('embed', 7)]], {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 0), ('anchor_id', 0), ('layout', 1), ('content', 8)]], {})}),
        ),
    ]
