# Generated by Django 5.2.7 on 2025-11-10 10:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 10), ('rich_text', 3), ('columns2', 5), ('columns3', 6), ('image', 7), ('embed', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table'], 'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid 2'), ('grid3', 'Grid 3')], 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table']}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed', 'h3', 'h4', 'table']}), 5: ('wagtail.blocks.StructBlock', [[('col1', 4), ('col2', 4)]], {}), 6: ('wagtail.blocks.StructBlock', [[('col1', 4), ('col2', 4), ('col3', 4)]], {}), 7: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 8: ('wagtail.blocks.URLBlock', (), {}), 9: ('wagtail.blocks.StreamBlock', [[('rich_text', 3), ('columns2', 5), ('columns3', 6), ('image', 7), ('embed', 8)]], {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 0), ('anchor_id', 0), ('optional_content', 1), ('layout', 2), ('content', 9)]], {})}),
        ),
    ]
