# Generated by Django 5.2.7 on 2025-11-10 11:09

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 16), ('rich_text', 4), ('columns2', 6), ('columns3', 7), ('image', 8), ('embed', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table'], 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Make section content collapsible', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid 2'), ('grid3', 'Grid 3')], 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table']}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed', 'h3', 'h4', 'table']}), 6: ('wagtail.blocks.StructBlock', [[('col1', 5), ('col2', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('col1', 5), ('col2', 5), ('col3', 5)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Paste video or media URL (YouTube, etc.)'}), 10: ('wagtail.blocks.CharBlock', (), {}), 11: ('wagtail.blocks.FloatBlock', (), {}), 12: ('wagtail.blocks.StructBlock', [[('label', 10), ('value', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {}), 14: ('wagtail.blocks.StructBlock', [[('title', 0), ('data', 13)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('rich_text', 4), ('columns2', 6), ('columns3', 7), ('image', 8), ('embed', 9), ('chart', 14)]], {'required': False}), 16: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 0), ('anchor_id', 0), ('optional_content', 1), ('collapsible', 2), ('layout', 3), ('content', 15)]], {}), 17: ('wagtail.blocks.URLBlock', (), {})}),
        ),
    ]
