# Generated by Django 5.2.7 on 2025-11-10 11:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section', 21), ('rich_text', 4), ('columns2', 6), ('columns3', 7), ('image', 8), ('embed', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table'], 'required': False}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Make section content collapsible', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('full', 'Full Width'), ('split', 'Two Columns'), ('grid2', 'Grid 2'), ('grid3', 'Grid 3')], 'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'hr', 'image', 'embed', 'code', 'h2', 'h3', 'h4', 'blockquote', 'table']}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'image', 'embed', 'h3', 'h4', 'table']}), 6: ('wagtail.blocks.StructBlock', [[('col1', 5), ('col2', 5)]], {}), 7: ('wagtail.blocks.StructBlock', [[('col1', 5), ('col2', 5), ('col3', 5)]], {}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Paste video or media URL (YouTube, etc.)'}), 10: ('wagtail.contrib.table_block.blocks.TableBlock', (), {}), 11: ('wagtail.documents.blocks.DocumentChooserBlock', (), {}), 12: ('wagtail.blocks.TextBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('document', 11), ('title', 0), ('description', 12)]], {}), 14: ('wagtail.blocks.CharBlock', (), {}), 15: ('wagtail.blocks.ListBlock', (14,), {}), 16: ('wagtail.blocks.FloatBlock', (), {}), 17: ('wagtail.blocks.StructBlock', [[('label', 14), ('value', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {}), 19: ('wagtail.blocks.StructBlock', [[('title', 0), ('data', 18)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('rich_text', 4), ('columns2', 6), ('columns3', 7), ('image', 8), ('embed', 9), ('table', 10), ('document', 13), ('tags', 15), ('chart', 19)]], {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 0), ('anchor_id', 0), ('optional_content', 1), ('collapsible', 2), ('layout', 3), ('content', 20)]], {}), 22: ('wagtail.blocks.URLBlock', (), {})}),
        ),
    ]
